run:
  timeout: 5m
  tests: false
  skip-dirs:
    - "(^|/)tests($|/)"
  output:
    format: colored-line-number
    print-issued-lines: true
    print-linter-name: true
    uniq-by-line: true
    path-prefix: ""
    sort-results: true
linters:
  enable:
    - depguard
    - errorlint
    - goconst
    - goimports
    - gosec
    - unconvert
